### ISSUE TITLE
Content hanging off the left and truncated on the right when navigating

### ISSUE THREAD

**Issue by swhitmore** [MediaBrowser/Emby.Theater.Windows#271] opened 2016-01-12 03:20 UTC
With the keyboard move up to the header row and keep moving right until the header scrolls then look at the content below. Then try moving one or two libraries to the left again and the content below will be hanging off the left and truncated on the right.

**Comment by LukePulverenti** [comment] 2016-01-14 06:02
duplicate of #264

**Closed by LukePulverenti** 2016-01-14 06:02 UTC
