### ISSUE TITLE
Detailed screen shows only episode title  

### ISSUE THREAD

**Issue by denz2** [MediaBrowser/Emby.Theater.Windows#346] opened 2016-03-23 03:18 UTC
The detailed screen doesn't show the series name only the episode title. I think it would be preferable to show both the series name and the episode title. Even in the main live tv screen at the bottom of the recording it shows the episode title when the recording thumbnail happens to be an add episode title doesn't mean much. 

Thanks

**Comment by LukePulverenti** [comment] 2016-05-05 18:19
Duplicate of #352

**Closed by LukePulverenti** 2016-05-05 18:19 UTC
